/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionControlForStlFilesRouteImport } from './routes/version-control-for-stl-files'
import { Route as VerifyEmailPendingRouteImport } from './routes/verify-email-pending'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TaggingSystemFor3dModelsRouteImport } from './routes/tagging-system-for-3d-models'
import { Route as TaggingStlFilesForFastSearchRouteImport } from './routes/tagging-stl-files-for-fast-search'
import { Route as StopStlFolderChaosRouteImport } from './routes/stop-stl-folder-chaos'
import { Route as StlVersionControlForMakersRouteImport } from './routes/stl-version-control-for-makers'
import { Route as StlShelfVsMarketplacesForPrivateLibrariesRouteImport } from './routes/stl-shelf-vs-marketplaces-for-private-libraries'
import { Route as StlShelfVsGoogleDriveForStlFilesRouteImport } from './routes/stl-shelf-vs-google-drive-for-stl-files'
import { Route as StlShelfVsFoldersRouteImport } from './routes/stl-shelf-vs-folders'
import { Route as StlShelfVsDropboxFor3dModelLibrariesRouteImport } from './routes/stl-shelf-vs-dropbox-for-3d-model-libraries'
import { Route as StlFileOrganizerRouteImport } from './routes/stl-file-organizer'
import { Route as StlFileManagementSoftwareRouteImport } from './routes/stl-file-management-software'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelfHostedStlFileLibraryRouteImport } from './routes/self-hosted-stl-file-library'
import { Route as SelfHosted3dModelLibrarySoftwareRouteImport } from './routes/self-hosted-3d-model-library-software'
import { Route as SelfHosted3dModelLibraryRouteImport } from './routes/self-hosted-3d-model-library'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivateSelfHostedStlLibraryRouteImport } from './routes/private-self-hosted-stl-library'
import { Route as Private3dModelLibrarySoftwareRouteImport } from './routes/private-3d-model-library-software'
import { Route as Private3dModelLibraryRouteImport } from './routes/private-3d-model-library'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrganizeStlFilesRouteImport } from './routes/organize-stl-files'
import { Route as OrganizeObjFilesFor3dPrintingRouteImport } from './routes/organize-obj-files-for-3d-printing'
import { Route as OrganizeObjFilesRouteImport } from './routes/organize-obj-files'
import { Route as Organize3mfFilesRouteImport } from './routes/organize-3mf-files'
import { Route as OpenSourceStlOrganizerRouteImport } from './routes/open-source-stl-organizer'
import { Route as OpenSourceStlLibrarySoftwareRouteImport } from './routes/open-source-stl-library-software'
import { Route as OpenSource3dModelLibrarySoftwareRouteImport } from './routes/open-source-3d-model-library-software'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HowToOrganizeStlFilesRouteImport } from './routes/how-to-organize-stl-files'
import { Route as HowToManageLargeStlLibrariesRouteImport } from './routes/how-to-manage-large-stl-libraries'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BestWayToOrganizeStlFilesRouteImport } from './routes/best-way-to-organize-stl-files'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R3dPrintFileOrganizationRouteImport } from './routes/3d-print-file-organization'
import { Route as R3dModelPreviewInBrowserRouteImport } from './routes/3d-model-preview-in-browser'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationSettingsRouteImport } from './routes/organization/settings'
import { Route as OrganizationMembersRouteImport } from './routes/organization/members'
import { Route as OrganizationCreateRouteImport } from './routes/organization/create'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutFailedRouteImport } from './routes/checkout/failed'
import { Route as ApiV1UploadRouteImport } from './routes/api/v1/upload'
import { Route as ApiV1ModelsRouteImport } from './routes/api/v1/models'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ModelsModelIdRouteImport } from './routes/api/v1/models.$modelId'
import { Route as ApiDownloadPrintProfileProfileIdRouteImport } from './routes/api/download/print-profile/$profileId'
import { Route as ApiDownloadFileFileIdRouteImport } from './routes/api/download/file/$fileId'
import { Route as ApiV1ModelsModelIdVersionsRouteImport } from './routes/api/v1/models.$modelId.versions'
import { Route as ApiDownloadVersionVersionIdZipRouteImport } from './routes/api/download/version/$versionId.zip'
import { Route as ApiV1ModelsModelIdFilesFileIdDownloadRouteImport } from './routes/api/v1/models.$modelId.files.$fileId.download'

const VersionControlForStlFilesRoute =
  VersionControlForStlFilesRouteImport.update({
    id: '/version-control-for-stl-files',
    path: '/version-control-for-stl-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyEmailPendingRoute = VerifyEmailPendingRouteImport.update({
  id: '/verify-email-pending',
  path: '/verify-email-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TaggingSystemFor3dModelsRoute =
  TaggingSystemFor3dModelsRouteImport.update({
    id: '/tagging-system-for-3d-models',
    path: '/tagging-system-for-3d-models',
    getParentRoute: () => rootRouteImport,
  } as any)
const TaggingStlFilesForFastSearchRoute =
  TaggingStlFilesForFastSearchRouteImport.update({
    id: '/tagging-stl-files-for-fast-search',
    path: '/tagging-stl-files-for-fast-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const StopStlFolderChaosRoute = StopStlFolderChaosRouteImport.update({
  id: '/stop-stl-folder-chaos',
  path: '/stop-stl-folder-chaos',
  getParentRoute: () => rootRouteImport,
} as any)
const StlVersionControlForMakersRoute =
  StlVersionControlForMakersRouteImport.update({
    id: '/stl-version-control-for-makers',
    path: '/stl-version-control-for-makers',
    getParentRoute: () => rootRouteImport,
  } as any)
const StlShelfVsMarketplacesForPrivateLibrariesRoute =
  StlShelfVsMarketplacesForPrivateLibrariesRouteImport.update({
    id: '/stl-shelf-vs-marketplaces-for-private-libraries',
    path: '/stl-shelf-vs-marketplaces-for-private-libraries',
    getParentRoute: () => rootRouteImport,
  } as any)
const StlShelfVsGoogleDriveForStlFilesRoute =
  StlShelfVsGoogleDriveForStlFilesRouteImport.update({
    id: '/stl-shelf-vs-google-drive-for-stl-files',
    path: '/stl-shelf-vs-google-drive-for-stl-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const StlShelfVsFoldersRoute = StlShelfVsFoldersRouteImport.update({
  id: '/stl-shelf-vs-folders',
  path: '/stl-shelf-vs-folders',
  getParentRoute: () => rootRouteImport,
} as any)
const StlShelfVsDropboxFor3dModelLibrariesRoute =
  StlShelfVsDropboxFor3dModelLibrariesRouteImport.update({
    id: '/stl-shelf-vs-dropbox-for-3d-model-libraries',
    path: '/stl-shelf-vs-dropbox-for-3d-model-libraries',
    getParentRoute: () => rootRouteImport,
  } as any)
const StlFileOrganizerRoute = StlFileOrganizerRouteImport.update({
  id: '/stl-file-organizer',
  path: '/stl-file-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const StlFileManagementSoftwareRoute =
  StlFileManagementSoftwareRouteImport.update({
    id: '/stl-file-management-software',
    path: '/stl-file-management-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostedStlFileLibraryRoute =
  SelfHostedStlFileLibraryRouteImport.update({
    id: '/self-hosted-stl-file-library',
    path: '/self-hosted-stl-file-library',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelfHosted3dModelLibrarySoftwareRoute =
  SelfHosted3dModelLibrarySoftwareRouteImport.update({
    id: '/self-hosted-3d-model-library-software',
    path: '/self-hosted-3d-model-library-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelfHosted3dModelLibraryRoute =
  SelfHosted3dModelLibraryRouteImport.update({
    id: '/self-hosted-3d-model-library',
    path: '/self-hosted-3d-model-library',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSelfHostedStlLibraryRoute =
  PrivateSelfHostedStlLibraryRouteImport.update({
    id: '/private-self-hosted-stl-library',
    path: '/private-self-hosted-stl-library',
    getParentRoute: () => rootRouteImport,
  } as any)
const Private3dModelLibrarySoftwareRoute =
  Private3dModelLibrarySoftwareRouteImport.update({
    id: '/private-3d-model-library-software',
    path: '/private-3d-model-library-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const Private3dModelLibraryRoute = Private3dModelLibraryRouteImport.update({
  id: '/private-3d-model-library',
  path: '/private-3d-model-library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeStlFilesRoute = OrganizeStlFilesRouteImport.update({
  id: '/organize-stl-files',
  path: '/organize-stl-files',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeObjFilesFor3dPrintingRoute =
  OrganizeObjFilesFor3dPrintingRouteImport.update({
    id: '/organize-obj-files-for-3d-printing',
    path: '/organize-obj-files-for-3d-printing',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizeObjFilesRoute = OrganizeObjFilesRouteImport.update({
  id: '/organize-obj-files',
  path: '/organize-obj-files',
  getParentRoute: () => rootRouteImport,
} as any)
const Organize3mfFilesRoute = Organize3mfFilesRouteImport.update({
  id: '/organize-3mf-files',
  path: '/organize-3mf-files',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceStlOrganizerRoute = OpenSourceStlOrganizerRouteImport.update({
  id: '/open-source-stl-organizer',
  path: '/open-source-stl-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceStlLibrarySoftwareRoute =
  OpenSourceStlLibrarySoftwareRouteImport.update({
    id: '/open-source-stl-library-software',
    path: '/open-source-stl-library-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpenSource3dModelLibrarySoftwareRoute =
  OpenSource3dModelLibrarySoftwareRouteImport.update({
    id: '/open-source-3d-model-library-software',
    path: '/open-source-3d-model-library-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOrganizeStlFilesRoute = HowToOrganizeStlFilesRouteImport.update({
  id: '/how-to-organize-stl-files',
  path: '/how-to-organize-stl-files',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToManageLargeStlLibrariesRoute =
  HowToManageLargeStlLibrariesRouteImport.update({
    id: '/how-to-manage-large-stl-libraries',
    path: '/how-to-manage-large-stl-libraries',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BestWayToOrganizeStlFilesRoute =
  BestWayToOrganizeStlFilesRouteImport.update({
    id: '/best-way-to-organize-stl-files',
    path: '/best-way-to-organize-stl-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dPrintFileOrganizationRoute =
  R3dPrintFileOrganizationRouteImport.update({
    id: '/3d-print-file-organization',
    path: '/3d-print-file-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const R3dModelPreviewInBrowserRoute =
  R3dModelPreviewInBrowserRouteImport.update({
    id: '/3d-model-preview-in-browser',
    path: '/3d-model-preview-in-browser',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization/settings',
  path: '/organization/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/organization/members',
  path: '/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCreateRoute = OrganizationCreateRouteImport.update({
  id: '/organization/create',
  path: '/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/checkout/failed',
  path: '/checkout/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UploadRoute = ApiV1UploadRouteImport.update({
  id: '/api/v1/upload',
  path: '/api/v1/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsRoute = ApiV1ModelsRouteImport.update({
  id: '/api/v1/models',
  path: '/api/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsModelIdRoute = ApiV1ModelsModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => ApiV1ModelsRoute,
} as any)
const ApiDownloadPrintProfileProfileIdRoute =
  ApiDownloadPrintProfileProfileIdRouteImport.update({
    id: '/api/download/print-profile/$profileId',
    path: '/api/download/print-profile/$profileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDownloadFileFileIdRoute = ApiDownloadFileFileIdRouteImport.update({
  id: '/api/download/file/$fileId',
  path: '/api/download/file/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsModelIdVersionsRoute =
  ApiV1ModelsModelIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ApiV1ModelsModelIdRoute,
  } as any)
const ApiDownloadVersionVersionIdZipRoute =
  ApiDownloadVersionVersionIdZipRouteImport.update({
    id: '/api/download/version/$versionId/zip',
    path: '/api/download/version/$versionId/zip',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ModelsModelIdFilesFileIdDownloadRoute =
  ApiV1ModelsModelIdFilesFileIdDownloadRouteImport.update({
    id: '/files/$fileId/download',
    path: '/files/$fileId/download',
    getParentRoute: () => ApiV1ModelsModelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-model-preview-in-browser': typeof R3dModelPreviewInBrowserRoute
  '/3d-print-file-organization': typeof R3dPrintFileOrganizationRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/announcements': typeof AnnouncementsRoute
  '/best-way-to-organize-stl-files': typeof BestWayToOrganizeStlFilesRoute
  '/billing': typeof BillingRoute
  '/consent': typeof ConsentRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guides': typeof GuidesRoute
  '/how-to-manage-large-stl-libraries': typeof HowToManageLargeStlLibrariesRoute
  '/how-to-organize-stl-files': typeof HowToOrganizeStlFilesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/open-source-3d-model-library-software': typeof OpenSource3dModelLibrarySoftwareRoute
  '/open-source-stl-library-software': typeof OpenSourceStlLibrarySoftwareRoute
  '/open-source-stl-organizer': typeof OpenSourceStlOrganizerRoute
  '/organize-3mf-files': typeof Organize3mfFilesRoute
  '/organize-obj-files': typeof OrganizeObjFilesRoute
  '/organize-obj-files-for-3d-printing': typeof OrganizeObjFilesFor3dPrintingRoute
  '/organize-stl-files': typeof OrganizeStlFilesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-3d-model-library': typeof Private3dModelLibraryRoute
  '/private-3d-model-library-software': typeof Private3dModelLibrarySoftwareRoute
  '/private-self-hosted-stl-library': typeof PrivateSelfHostedStlLibraryRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/self-hosted-3d-model-library': typeof SelfHosted3dModelLibraryRoute
  '/self-hosted-3d-model-library-software': typeof SelfHosted3dModelLibrarySoftwareRoute
  '/self-hosted-stl-file-library': typeof SelfHostedStlFileLibraryRoute
  '/signup': typeof SignupRoute
  '/stl-file-management-software': typeof StlFileManagementSoftwareRoute
  '/stl-file-organizer': typeof StlFileOrganizerRoute
  '/stl-shelf-vs-dropbox-for-3d-model-libraries': typeof StlShelfVsDropboxFor3dModelLibrariesRoute
  '/stl-shelf-vs-folders': typeof StlShelfVsFoldersRoute
  '/stl-shelf-vs-google-drive-for-stl-files': typeof StlShelfVsGoogleDriveForStlFilesRoute
  '/stl-shelf-vs-marketplaces-for-private-libraries': typeof StlShelfVsMarketplacesForPrivateLibrariesRoute
  '/stl-version-control-for-makers': typeof StlVersionControlForMakersRoute
  '/stop-stl-folder-chaos': typeof StopStlFolderChaosRoute
  '/tagging-stl-files-for-fast-search': typeof TaggingStlFilesForFastSearchRoute
  '/tagging-system-for-3d-models': typeof TaggingSystemFor3dModelsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/version-control-for-stl-files': typeof VersionControlForStlFilesRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/models': typeof ApiV1ModelsRouteWithChildren
  '/api/v1/upload': typeof ApiV1UploadRoute
  '/api/download/file/$fileId': typeof ApiDownloadFileFileIdRoute
  '/api/download/print-profile/$profileId': typeof ApiDownloadPrintProfileProfileIdRoute
  '/api/v1/models/$modelId': typeof ApiV1ModelsModelIdRouteWithChildren
  '/api/download/version/$versionId/zip': typeof ApiDownloadVersionVersionIdZipRoute
  '/api/v1/models/$modelId/versions': typeof ApiV1ModelsModelIdVersionsRoute
  '/api/v1/models/$modelId/files/$fileId/download': typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-model-preview-in-browser': typeof R3dModelPreviewInBrowserRoute
  '/3d-print-file-organization': typeof R3dPrintFileOrganizationRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/announcements': typeof AnnouncementsRoute
  '/best-way-to-organize-stl-files': typeof BestWayToOrganizeStlFilesRoute
  '/billing': typeof BillingRoute
  '/consent': typeof ConsentRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guides': typeof GuidesRoute
  '/how-to-manage-large-stl-libraries': typeof HowToManageLargeStlLibrariesRoute
  '/how-to-organize-stl-files': typeof HowToOrganizeStlFilesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/open-source-3d-model-library-software': typeof OpenSource3dModelLibrarySoftwareRoute
  '/open-source-stl-library-software': typeof OpenSourceStlLibrarySoftwareRoute
  '/open-source-stl-organizer': typeof OpenSourceStlOrganizerRoute
  '/organize-3mf-files': typeof Organize3mfFilesRoute
  '/organize-obj-files': typeof OrganizeObjFilesRoute
  '/organize-obj-files-for-3d-printing': typeof OrganizeObjFilesFor3dPrintingRoute
  '/organize-stl-files': typeof OrganizeStlFilesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-3d-model-library': typeof Private3dModelLibraryRoute
  '/private-3d-model-library-software': typeof Private3dModelLibrarySoftwareRoute
  '/private-self-hosted-stl-library': typeof PrivateSelfHostedStlLibraryRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/self-hosted-3d-model-library': typeof SelfHosted3dModelLibraryRoute
  '/self-hosted-3d-model-library-software': typeof SelfHosted3dModelLibrarySoftwareRoute
  '/self-hosted-stl-file-library': typeof SelfHostedStlFileLibraryRoute
  '/signup': typeof SignupRoute
  '/stl-file-management-software': typeof StlFileManagementSoftwareRoute
  '/stl-file-organizer': typeof StlFileOrganizerRoute
  '/stl-shelf-vs-dropbox-for-3d-model-libraries': typeof StlShelfVsDropboxFor3dModelLibrariesRoute
  '/stl-shelf-vs-folders': typeof StlShelfVsFoldersRoute
  '/stl-shelf-vs-google-drive-for-stl-files': typeof StlShelfVsGoogleDriveForStlFilesRoute
  '/stl-shelf-vs-marketplaces-for-private-libraries': typeof StlShelfVsMarketplacesForPrivateLibrariesRoute
  '/stl-version-control-for-makers': typeof StlVersionControlForMakersRoute
  '/stop-stl-folder-chaos': typeof StopStlFolderChaosRoute
  '/tagging-stl-files-for-fast-search': typeof TaggingStlFilesForFastSearchRoute
  '/tagging-system-for-3d-models': typeof TaggingSystemFor3dModelsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/version-control-for-stl-files': typeof VersionControlForStlFilesRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/models': typeof ApiV1ModelsRouteWithChildren
  '/api/v1/upload': typeof ApiV1UploadRoute
  '/api/download/file/$fileId': typeof ApiDownloadFileFileIdRoute
  '/api/download/print-profile/$profileId': typeof ApiDownloadPrintProfileProfileIdRoute
  '/api/v1/models/$modelId': typeof ApiV1ModelsModelIdRouteWithChildren
  '/api/download/version/$versionId/zip': typeof ApiDownloadVersionVersionIdZipRoute
  '/api/v1/models/$modelId/versions': typeof ApiV1ModelsModelIdVersionsRoute
  '/api/v1/models/$modelId/files/$fileId/download': typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-model-preview-in-browser': typeof R3dModelPreviewInBrowserRoute
  '/3d-print-file-organization': typeof R3dPrintFileOrganizationRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/announcements': typeof AnnouncementsRoute
  '/best-way-to-organize-stl-files': typeof BestWayToOrganizeStlFilesRoute
  '/billing': typeof BillingRoute
  '/consent': typeof ConsentRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guides': typeof GuidesRoute
  '/how-to-manage-large-stl-libraries': typeof HowToManageLargeStlLibrariesRoute
  '/how-to-organize-stl-files': typeof HowToOrganizeStlFilesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/open-source-3d-model-library-software': typeof OpenSource3dModelLibrarySoftwareRoute
  '/open-source-stl-library-software': typeof OpenSourceStlLibrarySoftwareRoute
  '/open-source-stl-organizer': typeof OpenSourceStlOrganizerRoute
  '/organize-3mf-files': typeof Organize3mfFilesRoute
  '/organize-obj-files': typeof OrganizeObjFilesRoute
  '/organize-obj-files-for-3d-printing': typeof OrganizeObjFilesFor3dPrintingRoute
  '/organize-stl-files': typeof OrganizeStlFilesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-3d-model-library': typeof Private3dModelLibraryRoute
  '/private-3d-model-library-software': typeof Private3dModelLibrarySoftwareRoute
  '/private-self-hosted-stl-library': typeof PrivateSelfHostedStlLibraryRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/self-hosted-3d-model-library': typeof SelfHosted3dModelLibraryRoute
  '/self-hosted-3d-model-library-software': typeof SelfHosted3dModelLibrarySoftwareRoute
  '/self-hosted-stl-file-library': typeof SelfHostedStlFileLibraryRoute
  '/signup': typeof SignupRoute
  '/stl-file-management-software': typeof StlFileManagementSoftwareRoute
  '/stl-file-organizer': typeof StlFileOrganizerRoute
  '/stl-shelf-vs-dropbox-for-3d-model-libraries': typeof StlShelfVsDropboxFor3dModelLibrariesRoute
  '/stl-shelf-vs-folders': typeof StlShelfVsFoldersRoute
  '/stl-shelf-vs-google-drive-for-stl-files': typeof StlShelfVsGoogleDriveForStlFilesRoute
  '/stl-shelf-vs-marketplaces-for-private-libraries': typeof StlShelfVsMarketplacesForPrivateLibrariesRoute
  '/stl-version-control-for-makers': typeof StlVersionControlForMakersRoute
  '/stop-stl-folder-chaos': typeof StopStlFolderChaosRoute
  '/tagging-stl-files-for-fast-search': typeof TaggingStlFilesForFastSearchRoute
  '/tagging-system-for-3d-models': typeof TaggingSystemFor3dModelsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/version-control-for-stl-files': typeof VersionControlForStlFilesRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/models': typeof ApiV1ModelsRouteWithChildren
  '/api/v1/upload': typeof ApiV1UploadRoute
  '/api/download/file/$fileId': typeof ApiDownloadFileFileIdRoute
  '/api/download/print-profile/$profileId': typeof ApiDownloadPrintProfileProfileIdRoute
  '/api/v1/models/$modelId': typeof ApiV1ModelsModelIdRouteWithChildren
  '/api/download/version/$versionId/zip': typeof ApiDownloadVersionVersionIdZipRoute
  '/api/v1/models/$modelId/versions': typeof ApiV1ModelsModelIdVersionsRoute
  '/api/v1/models/$modelId/files/$fileId/download': typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-model-preview-in-browser'
    | '/3d-print-file-organization'
    | '/about'
    | '/accept-invitation'
    | '/announcements'
    | '/best-way-to-organize-stl-files'
    | '/billing'
    | '/consent'
    | '/faqs'
    | '/forgot-password'
    | '/guides'
    | '/how-to-manage-large-stl-libraries'
    | '/how-to-organize-stl-files'
    | '/library'
    | '/login'
    | '/open-source-3d-model-library-software'
    | '/open-source-stl-library-software'
    | '/open-source-stl-organizer'
    | '/organize-3mf-files'
    | '/organize-obj-files'
    | '/organize-obj-files-for-3d-printing'
    | '/organize-stl-files'
    | '/pricing'
    | '/privacy'
    | '/private-3d-model-library'
    | '/private-3d-model-library-software'
    | '/private-self-hosted-stl-library'
    | '/profile'
    | '/reset-password'
    | '/self-hosted-3d-model-library'
    | '/self-hosted-3d-model-library-software'
    | '/self-hosted-stl-file-library'
    | '/signup'
    | '/stl-file-management-software'
    | '/stl-file-organizer'
    | '/stl-shelf-vs-dropbox-for-3d-model-libraries'
    | '/stl-shelf-vs-folders'
    | '/stl-shelf-vs-google-drive-for-stl-files'
    | '/stl-shelf-vs-marketplaces-for-private-libraries'
    | '/stl-version-control-for-makers'
    | '/stop-stl-folder-chaos'
    | '/tagging-stl-files-for-fast-search'
    | '/tagging-system-for-3d-models'
    | '/terms'
    | '/verify-email'
    | '/verify-email-pending'
    | '/version-control-for-stl-files'
    | '/checkout/failed'
    | '/checkout/success'
    | '/models/$modelId'
    | '/organization/create'
    | '/organization/members'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/v1/models'
    | '/api/v1/upload'
    | '/api/download/file/$fileId'
    | '/api/download/print-profile/$profileId'
    | '/api/v1/models/$modelId'
    | '/api/download/version/$versionId/zip'
    | '/api/v1/models/$modelId/versions'
    | '/api/v1/models/$modelId/files/$fileId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-model-preview-in-browser'
    | '/3d-print-file-organization'
    | '/about'
    | '/accept-invitation'
    | '/announcements'
    | '/best-way-to-organize-stl-files'
    | '/billing'
    | '/consent'
    | '/faqs'
    | '/forgot-password'
    | '/guides'
    | '/how-to-manage-large-stl-libraries'
    | '/how-to-organize-stl-files'
    | '/library'
    | '/login'
    | '/open-source-3d-model-library-software'
    | '/open-source-stl-library-software'
    | '/open-source-stl-organizer'
    | '/organize-3mf-files'
    | '/organize-obj-files'
    | '/organize-obj-files-for-3d-printing'
    | '/organize-stl-files'
    | '/pricing'
    | '/privacy'
    | '/private-3d-model-library'
    | '/private-3d-model-library-software'
    | '/private-self-hosted-stl-library'
    | '/profile'
    | '/reset-password'
    | '/self-hosted-3d-model-library'
    | '/self-hosted-3d-model-library-software'
    | '/self-hosted-stl-file-library'
    | '/signup'
    | '/stl-file-management-software'
    | '/stl-file-organizer'
    | '/stl-shelf-vs-dropbox-for-3d-model-libraries'
    | '/stl-shelf-vs-folders'
    | '/stl-shelf-vs-google-drive-for-stl-files'
    | '/stl-shelf-vs-marketplaces-for-private-libraries'
    | '/stl-version-control-for-makers'
    | '/stop-stl-folder-chaos'
    | '/tagging-stl-files-for-fast-search'
    | '/tagging-system-for-3d-models'
    | '/terms'
    | '/verify-email'
    | '/verify-email-pending'
    | '/version-control-for-stl-files'
    | '/checkout/failed'
    | '/checkout/success'
    | '/models/$modelId'
    | '/organization/create'
    | '/organization/members'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/v1/models'
    | '/api/v1/upload'
    | '/api/download/file/$fileId'
    | '/api/download/print-profile/$profileId'
    | '/api/v1/models/$modelId'
    | '/api/download/version/$versionId/zip'
    | '/api/v1/models/$modelId/versions'
    | '/api/v1/models/$modelId/files/$fileId/download'
  id:
    | '__root__'
    | '/'
    | '/3d-model-preview-in-browser'
    | '/3d-print-file-organization'
    | '/about'
    | '/accept-invitation'
    | '/announcements'
    | '/best-way-to-organize-stl-files'
    | '/billing'
    | '/consent'
    | '/faqs'
    | '/forgot-password'
    | '/guides'
    | '/how-to-manage-large-stl-libraries'
    | '/how-to-organize-stl-files'
    | '/library'
    | '/login'
    | '/open-source-3d-model-library-software'
    | '/open-source-stl-library-software'
    | '/open-source-stl-organizer'
    | '/organize-3mf-files'
    | '/organize-obj-files'
    | '/organize-obj-files-for-3d-printing'
    | '/organize-stl-files'
    | '/pricing'
    | '/privacy'
    | '/private-3d-model-library'
    | '/private-3d-model-library-software'
    | '/private-self-hosted-stl-library'
    | '/profile'
    | '/reset-password'
    | '/self-hosted-3d-model-library'
    | '/self-hosted-3d-model-library-software'
    | '/self-hosted-stl-file-library'
    | '/signup'
    | '/stl-file-management-software'
    | '/stl-file-organizer'
    | '/stl-shelf-vs-dropbox-for-3d-model-libraries'
    | '/stl-shelf-vs-folders'
    | '/stl-shelf-vs-google-drive-for-stl-files'
    | '/stl-shelf-vs-marketplaces-for-private-libraries'
    | '/stl-version-control-for-makers'
    | '/stop-stl-folder-chaos'
    | '/tagging-stl-files-for-fast-search'
    | '/tagging-system-for-3d-models'
    | '/terms'
    | '/verify-email'
    | '/verify-email-pending'
    | '/version-control-for-stl-files'
    | '/checkout/failed'
    | '/checkout/success'
    | '/models/$modelId'
    | '/organization/create'
    | '/organization/members'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/v1/models'
    | '/api/v1/upload'
    | '/api/download/file/$fileId'
    | '/api/download/print-profile/$profileId'
    | '/api/v1/models/$modelId'
    | '/api/download/version/$versionId/zip'
    | '/api/v1/models/$modelId/versions'
    | '/api/v1/models/$modelId/files/$fileId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dModelPreviewInBrowserRoute: typeof R3dModelPreviewInBrowserRoute
  R3dPrintFileOrganizationRoute: typeof R3dPrintFileOrganizationRoute
  AboutRoute: typeof AboutRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  BestWayToOrganizeStlFilesRoute: typeof BestWayToOrganizeStlFilesRoute
  BillingRoute: typeof BillingRoute
  ConsentRoute: typeof ConsentRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidesRoute: typeof GuidesRoute
  HowToManageLargeStlLibrariesRoute: typeof HowToManageLargeStlLibrariesRoute
  HowToOrganizeStlFilesRoute: typeof HowToOrganizeStlFilesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OpenSource3dModelLibrarySoftwareRoute: typeof OpenSource3dModelLibrarySoftwareRoute
  OpenSourceStlLibrarySoftwareRoute: typeof OpenSourceStlLibrarySoftwareRoute
  OpenSourceStlOrganizerRoute: typeof OpenSourceStlOrganizerRoute
  Organize3mfFilesRoute: typeof Organize3mfFilesRoute
  OrganizeObjFilesRoute: typeof OrganizeObjFilesRoute
  OrganizeObjFilesFor3dPrintingRoute: typeof OrganizeObjFilesFor3dPrintingRoute
  OrganizeStlFilesRoute: typeof OrganizeStlFilesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  Private3dModelLibraryRoute: typeof Private3dModelLibraryRoute
  Private3dModelLibrarySoftwareRoute: typeof Private3dModelLibrarySoftwareRoute
  PrivateSelfHostedStlLibraryRoute: typeof PrivateSelfHostedStlLibraryRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelfHosted3dModelLibraryRoute: typeof SelfHosted3dModelLibraryRoute
  SelfHosted3dModelLibrarySoftwareRoute: typeof SelfHosted3dModelLibrarySoftwareRoute
  SelfHostedStlFileLibraryRoute: typeof SelfHostedStlFileLibraryRoute
  SignupRoute: typeof SignupRoute
  StlFileManagementSoftwareRoute: typeof StlFileManagementSoftwareRoute
  StlFileOrganizerRoute: typeof StlFileOrganizerRoute
  StlShelfVsDropboxFor3dModelLibrariesRoute: typeof StlShelfVsDropboxFor3dModelLibrariesRoute
  StlShelfVsFoldersRoute: typeof StlShelfVsFoldersRoute
  StlShelfVsGoogleDriveForStlFilesRoute: typeof StlShelfVsGoogleDriveForStlFilesRoute
  StlShelfVsMarketplacesForPrivateLibrariesRoute: typeof StlShelfVsMarketplacesForPrivateLibrariesRoute
  StlVersionControlForMakersRoute: typeof StlVersionControlForMakersRoute
  StopStlFolderChaosRoute: typeof StopStlFolderChaosRoute
  TaggingStlFilesForFastSearchRoute: typeof TaggingStlFilesForFastSearchRoute
  TaggingSystemFor3dModelsRoute: typeof TaggingSystemFor3dModelsRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyEmailPendingRoute: typeof VerifyEmailPendingRoute
  VersionControlForStlFilesRoute: typeof VersionControlForStlFilesRoute
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  OrganizationCreateRoute: typeof OrganizationCreateRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ModelsRoute: typeof ApiV1ModelsRouteWithChildren
  ApiV1UploadRoute: typeof ApiV1UploadRoute
  ApiDownloadFileFileIdRoute: typeof ApiDownloadFileFileIdRoute
  ApiDownloadPrintProfileProfileIdRoute: typeof ApiDownloadPrintProfileProfileIdRoute
  ApiDownloadVersionVersionIdZipRoute: typeof ApiDownloadVersionVersionIdZipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version-control-for-stl-files': {
      id: '/version-control-for-stl-files'
      path: '/version-control-for-stl-files'
      fullPath: '/version-control-for-stl-files'
      preLoaderRoute: typeof VersionControlForStlFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email-pending': {
      id: '/verify-email-pending'
      path: '/verify-email-pending'
      fullPath: '/verify-email-pending'
      preLoaderRoute: typeof VerifyEmailPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagging-system-for-3d-models': {
      id: '/tagging-system-for-3d-models'
      path: '/tagging-system-for-3d-models'
      fullPath: '/tagging-system-for-3d-models'
      preLoaderRoute: typeof TaggingSystemFor3dModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagging-stl-files-for-fast-search': {
      id: '/tagging-stl-files-for-fast-search'
      path: '/tagging-stl-files-for-fast-search'
      fullPath: '/tagging-stl-files-for-fast-search'
      preLoaderRoute: typeof TaggingStlFilesForFastSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop-stl-folder-chaos': {
      id: '/stop-stl-folder-chaos'
      path: '/stop-stl-folder-chaos'
      fullPath: '/stop-stl-folder-chaos'
      preLoaderRoute: typeof StopStlFolderChaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-version-control-for-makers': {
      id: '/stl-version-control-for-makers'
      path: '/stl-version-control-for-makers'
      fullPath: '/stl-version-control-for-makers'
      preLoaderRoute: typeof StlVersionControlForMakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-shelf-vs-marketplaces-for-private-libraries': {
      id: '/stl-shelf-vs-marketplaces-for-private-libraries'
      path: '/stl-shelf-vs-marketplaces-for-private-libraries'
      fullPath: '/stl-shelf-vs-marketplaces-for-private-libraries'
      preLoaderRoute: typeof StlShelfVsMarketplacesForPrivateLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-shelf-vs-google-drive-for-stl-files': {
      id: '/stl-shelf-vs-google-drive-for-stl-files'
      path: '/stl-shelf-vs-google-drive-for-stl-files'
      fullPath: '/stl-shelf-vs-google-drive-for-stl-files'
      preLoaderRoute: typeof StlShelfVsGoogleDriveForStlFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-shelf-vs-folders': {
      id: '/stl-shelf-vs-folders'
      path: '/stl-shelf-vs-folders'
      fullPath: '/stl-shelf-vs-folders'
      preLoaderRoute: typeof StlShelfVsFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-shelf-vs-dropbox-for-3d-model-libraries': {
      id: '/stl-shelf-vs-dropbox-for-3d-model-libraries'
      path: '/stl-shelf-vs-dropbox-for-3d-model-libraries'
      fullPath: '/stl-shelf-vs-dropbox-for-3d-model-libraries'
      preLoaderRoute: typeof StlShelfVsDropboxFor3dModelLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-file-organizer': {
      id: '/stl-file-organizer'
      path: '/stl-file-organizer'
      fullPath: '/stl-file-organizer'
      preLoaderRoute: typeof StlFileOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stl-file-management-software': {
      id: '/stl-file-management-software'
      path: '/stl-file-management-software'
      fullPath: '/stl-file-management-software'
      preLoaderRoute: typeof StlFileManagementSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosted-stl-file-library': {
      id: '/self-hosted-stl-file-library'
      path: '/self-hosted-stl-file-library'
      fullPath: '/self-hosted-stl-file-library'
      preLoaderRoute: typeof SelfHostedStlFileLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosted-3d-model-library-software': {
      id: '/self-hosted-3d-model-library-software'
      path: '/self-hosted-3d-model-library-software'
      fullPath: '/self-hosted-3d-model-library-software'
      preLoaderRoute: typeof SelfHosted3dModelLibrarySoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosted-3d-model-library': {
      id: '/self-hosted-3d-model-library'
      path: '/self-hosted-3d-model-library'
      fullPath: '/self-hosted-3d-model-library'
      preLoaderRoute: typeof SelfHosted3dModelLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-self-hosted-stl-library': {
      id: '/private-self-hosted-stl-library'
      path: '/private-self-hosted-stl-library'
      fullPath: '/private-self-hosted-stl-library'
      preLoaderRoute: typeof PrivateSelfHostedStlLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-3d-model-library-software': {
      id: '/private-3d-model-library-software'
      path: '/private-3d-model-library-software'
      fullPath: '/private-3d-model-library-software'
      preLoaderRoute: typeof Private3dModelLibrarySoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-3d-model-library': {
      id: '/private-3d-model-library'
      path: '/private-3d-model-library'
      fullPath: '/private-3d-model-library'
      preLoaderRoute: typeof Private3dModelLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize-stl-files': {
      id: '/organize-stl-files'
      path: '/organize-stl-files'
      fullPath: '/organize-stl-files'
      preLoaderRoute: typeof OrganizeStlFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize-obj-files-for-3d-printing': {
      id: '/organize-obj-files-for-3d-printing'
      path: '/organize-obj-files-for-3d-printing'
      fullPath: '/organize-obj-files-for-3d-printing'
      preLoaderRoute: typeof OrganizeObjFilesFor3dPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize-obj-files': {
      id: '/organize-obj-files'
      path: '/organize-obj-files'
      fullPath: '/organize-obj-files'
      preLoaderRoute: typeof OrganizeObjFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize-3mf-files': {
      id: '/organize-3mf-files'
      path: '/organize-3mf-files'
      fullPath: '/organize-3mf-files'
      preLoaderRoute: typeof Organize3mfFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source-stl-organizer': {
      id: '/open-source-stl-organizer'
      path: '/open-source-stl-organizer'
      fullPath: '/open-source-stl-organizer'
      preLoaderRoute: typeof OpenSourceStlOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source-stl-library-software': {
      id: '/open-source-stl-library-software'
      path: '/open-source-stl-library-software'
      fullPath: '/open-source-stl-library-software'
      preLoaderRoute: typeof OpenSourceStlLibrarySoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source-3d-model-library-software': {
      id: '/open-source-3d-model-library-software'
      path: '/open-source-3d-model-library-software'
      fullPath: '/open-source-3d-model-library-software'
      preLoaderRoute: typeof OpenSource3dModelLibrarySoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-organize-stl-files': {
      id: '/how-to-organize-stl-files'
      path: '/how-to-organize-stl-files'
      fullPath: '/how-to-organize-stl-files'
      preLoaderRoute: typeof HowToOrganizeStlFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-manage-large-stl-libraries': {
      id: '/how-to-manage-large-stl-libraries'
      path: '/how-to-manage-large-stl-libraries'
      fullPath: '/how-to-manage-large-stl-libraries'
      preLoaderRoute: typeof HowToManageLargeStlLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-way-to-organize-stl-files': {
      id: '/best-way-to-organize-stl-files'
      path: '/best-way-to-organize-stl-files'
      fullPath: '/best-way-to-organize-stl-files'
      preLoaderRoute: typeof BestWayToOrganizeStlFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-print-file-organization': {
      id: '/3d-print-file-organization'
      path: '/3d-print-file-organization'
      fullPath: '/3d-print-file-organization'
      preLoaderRoute: typeof R3dPrintFileOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-model-preview-in-browser': {
      id: '/3d-model-preview-in-browser'
      path: '/3d-model-preview-in-browser'
      fullPath: '/3d-model-preview-in-browser'
      preLoaderRoute: typeof R3dModelPreviewInBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/organization/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/checkout/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/upload': {
      id: '/api/v1/upload'
      path: '/api/v1/upload'
      fullPath: '/api/v1/upload'
      preLoaderRoute: typeof ApiV1UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models': {
      id: '/api/v1/models'
      path: '/api/v1/models'
      fullPath: '/api/v1/models'
      preLoaderRoute: typeof ApiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models/$modelId': {
      id: '/api/v1/models/$modelId'
      path: '/$modelId'
      fullPath: '/api/v1/models/$modelId'
      preLoaderRoute: typeof ApiV1ModelsModelIdRouteImport
      parentRoute: typeof ApiV1ModelsRoute
    }
    '/api/download/print-profile/$profileId': {
      id: '/api/download/print-profile/$profileId'
      path: '/api/download/print-profile/$profileId'
      fullPath: '/api/download/print-profile/$profileId'
      preLoaderRoute: typeof ApiDownloadPrintProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/file/$fileId': {
      id: '/api/download/file/$fileId'
      path: '/api/download/file/$fileId'
      fullPath: '/api/download/file/$fileId'
      preLoaderRoute: typeof ApiDownloadFileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models/$modelId/versions': {
      id: '/api/v1/models/$modelId/versions'
      path: '/versions'
      fullPath: '/api/v1/models/$modelId/versions'
      preLoaderRoute: typeof ApiV1ModelsModelIdVersionsRouteImport
      parentRoute: typeof ApiV1ModelsModelIdRoute
    }
    '/api/download/version/$versionId/zip': {
      id: '/api/download/version/$versionId/zip'
      path: '/api/download/version/$versionId/zip'
      fullPath: '/api/download/version/$versionId/zip'
      preLoaderRoute: typeof ApiDownloadVersionVersionIdZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models/$modelId/files/$fileId/download': {
      id: '/api/v1/models/$modelId/files/$fileId/download'
      path: '/files/$fileId/download'
      fullPath: '/api/v1/models/$modelId/files/$fileId/download'
      preLoaderRoute: typeof ApiV1ModelsModelIdFilesFileIdDownloadRouteImport
      parentRoute: typeof ApiV1ModelsModelIdRoute
    }
  }
}

interface ApiV1ModelsModelIdRouteChildren {
  ApiV1ModelsModelIdVersionsRoute: typeof ApiV1ModelsModelIdVersionsRoute
  ApiV1ModelsModelIdFilesFileIdDownloadRoute: typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}

const ApiV1ModelsModelIdRouteChildren: ApiV1ModelsModelIdRouteChildren = {
  ApiV1ModelsModelIdVersionsRoute: ApiV1ModelsModelIdVersionsRoute,
  ApiV1ModelsModelIdFilesFileIdDownloadRoute:
    ApiV1ModelsModelIdFilesFileIdDownloadRoute,
}

const ApiV1ModelsModelIdRouteWithChildren =
  ApiV1ModelsModelIdRoute._addFileChildren(ApiV1ModelsModelIdRouteChildren)

interface ApiV1ModelsRouteChildren {
  ApiV1ModelsModelIdRoute: typeof ApiV1ModelsModelIdRouteWithChildren
}

const ApiV1ModelsRouteChildren: ApiV1ModelsRouteChildren = {
  ApiV1ModelsModelIdRoute: ApiV1ModelsModelIdRouteWithChildren,
}

const ApiV1ModelsRouteWithChildren = ApiV1ModelsRoute._addFileChildren(
  ApiV1ModelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dModelPreviewInBrowserRoute: R3dModelPreviewInBrowserRoute,
  R3dPrintFileOrganizationRoute: R3dPrintFileOrganizationRoute,
  AboutRoute: AboutRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  BestWayToOrganizeStlFilesRoute: BestWayToOrganizeStlFilesRoute,
  BillingRoute: BillingRoute,
  ConsentRoute: ConsentRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidesRoute: GuidesRoute,
  HowToManageLargeStlLibrariesRoute: HowToManageLargeStlLibrariesRoute,
  HowToOrganizeStlFilesRoute: HowToOrganizeStlFilesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OpenSource3dModelLibrarySoftwareRoute: OpenSource3dModelLibrarySoftwareRoute,
  OpenSourceStlLibrarySoftwareRoute: OpenSourceStlLibrarySoftwareRoute,
  OpenSourceStlOrganizerRoute: OpenSourceStlOrganizerRoute,
  Organize3mfFilesRoute: Organize3mfFilesRoute,
  OrganizeObjFilesRoute: OrganizeObjFilesRoute,
  OrganizeObjFilesFor3dPrintingRoute: OrganizeObjFilesFor3dPrintingRoute,
  OrganizeStlFilesRoute: OrganizeStlFilesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  Private3dModelLibraryRoute: Private3dModelLibraryRoute,
  Private3dModelLibrarySoftwareRoute: Private3dModelLibrarySoftwareRoute,
  PrivateSelfHostedStlLibraryRoute: PrivateSelfHostedStlLibraryRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelfHosted3dModelLibraryRoute: SelfHosted3dModelLibraryRoute,
  SelfHosted3dModelLibrarySoftwareRoute: SelfHosted3dModelLibrarySoftwareRoute,
  SelfHostedStlFileLibraryRoute: SelfHostedStlFileLibraryRoute,
  SignupRoute: SignupRoute,
  StlFileManagementSoftwareRoute: StlFileManagementSoftwareRoute,
  StlFileOrganizerRoute: StlFileOrganizerRoute,
  StlShelfVsDropboxFor3dModelLibrariesRoute:
    StlShelfVsDropboxFor3dModelLibrariesRoute,
  StlShelfVsFoldersRoute: StlShelfVsFoldersRoute,
  StlShelfVsGoogleDriveForStlFilesRoute: StlShelfVsGoogleDriveForStlFilesRoute,
  StlShelfVsMarketplacesForPrivateLibrariesRoute:
    StlShelfVsMarketplacesForPrivateLibrariesRoute,
  StlVersionControlForMakersRoute: StlVersionControlForMakersRoute,
  StopStlFolderChaosRoute: StopStlFolderChaosRoute,
  TaggingStlFilesForFastSearchRoute: TaggingStlFilesForFastSearchRoute,
  TaggingSystemFor3dModelsRoute: TaggingSystemFor3dModelsRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyEmailPendingRoute: VerifyEmailPendingRoute,
  VersionControlForStlFilesRoute: VersionControlForStlFilesRoute,
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  OrganizationCreateRoute: OrganizationCreateRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ModelsRoute: ApiV1ModelsRouteWithChildren,
  ApiV1UploadRoute: ApiV1UploadRoute,
  ApiDownloadFileFileIdRoute: ApiDownloadFileFileIdRoute,
  ApiDownloadPrintProfileProfileIdRoute: ApiDownloadPrintProfileProfileIdRoute,
  ApiDownloadVersionVersionIdZipRoute: ApiDownloadVersionVersionIdZipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
