/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationSettingsRouteImport } from './routes/organization/settings'
import { Route as OrganizationMembersRouteImport } from './routes/organization/members'
import { Route as OrganizationCreateRouteImport } from './routes/organization/create'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiV1UploadRouteImport } from './routes/api/v1/upload'
import { Route as ApiV1ModelsRouteImport } from './routes/api/v1/models'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ModelsModelIdRouteImport } from './routes/api/v1/models.$modelId'
import { Route as ApiAuthMagicLinkVerifyRouteImport } from './routes/api/auth/magic-link/verify'
import { Route as ApiV1ModelsModelIdVersionsRouteImport } from './routes/api/v1/models.$modelId.versions'
import { Route as ApiV1ModelsModelIdFilesFileIdDownloadRouteImport } from './routes/api/v1/models.$modelId.files.$fileId.download'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization/settings',
  path: '/organization/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/organization/members',
  path: '/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCreateRoute = OrganizationCreateRouteImport.update({
  id: '/organization/create',
  path: '/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UploadRoute = ApiV1UploadRouteImport.update({
  id: '/api/v1/upload',
  path: '/api/v1/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsRoute = ApiV1ModelsRouteImport.update({
  id: '/api/v1/models',
  path: '/api/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsModelIdRoute = ApiV1ModelsModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => ApiV1ModelsRoute,
} as any)
const ApiAuthMagicLinkVerifyRoute = ApiAuthMagicLinkVerifyRouteImport.update({
  id: '/api/auth/magic-link/verify',
  path: '/api/auth/magic-link/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsModelIdVersionsRoute =
  ApiV1ModelsModelIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ApiV1ModelsModelIdRoute,
  } as any)
const ApiV1ModelsModelIdFilesFileIdDownloadRoute =
  ApiV1ModelsModelIdFilesFileIdDownloadRouteImport.update({
    id: '/files/$fileId/download',
    path: '/files/$fileId/download',
    getParentRoute: () => ApiV1ModelsModelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/models': typeof ApiV1ModelsRouteWithChildren
  '/api/v1/upload': typeof ApiV1UploadRoute
  '/api/auth/magic-link/verify': typeof ApiAuthMagicLinkVerifyRoute
  '/api/v1/models/$modelId': typeof ApiV1ModelsModelIdRouteWithChildren
  '/api/v1/models/$modelId/versions': typeof ApiV1ModelsModelIdVersionsRoute
  '/api/v1/models/$modelId/files/$fileId/download': typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/models': typeof ApiV1ModelsRouteWithChildren
  '/api/v1/upload': typeof ApiV1UploadRoute
  '/api/auth/magic-link/verify': typeof ApiAuthMagicLinkVerifyRoute
  '/api/v1/models/$modelId': typeof ApiV1ModelsModelIdRouteWithChildren
  '/api/v1/models/$modelId/versions': typeof ApiV1ModelsModelIdVersionsRoute
  '/api/v1/models/$modelId/files/$fileId/download': typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/models': typeof ApiV1ModelsRouteWithChildren
  '/api/v1/upload': typeof ApiV1UploadRoute
  '/api/auth/magic-link/verify': typeof ApiAuthMagicLinkVerifyRoute
  '/api/v1/models/$modelId': typeof ApiV1ModelsModelIdRouteWithChildren
  '/api/v1/models/$modelId/versions': typeof ApiV1ModelsModelIdVersionsRoute
  '/api/v1/models/$modelId/files/$fileId/download': typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/billing'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/checkout/success'
    | '/models/$modelId'
    | '/organization/create'
    | '/organization/members'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/v1/models'
    | '/api/v1/upload'
    | '/api/auth/magic-link/verify'
    | '/api/v1/models/$modelId'
    | '/api/v1/models/$modelId/versions'
    | '/api/v1/models/$modelId/files/$fileId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/checkout/success'
    | '/models/$modelId'
    | '/organization/create'
    | '/organization/members'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/v1/models'
    | '/api/v1/upload'
    | '/api/auth/magic-link/verify'
    | '/api/v1/models/$modelId'
    | '/api/v1/models/$modelId/versions'
    | '/api/v1/models/$modelId/files/$fileId/download'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/billing'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/checkout/success'
    | '/models/$modelId'
    | '/organization/create'
    | '/organization/members'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/v1/models'
    | '/api/v1/upload'
    | '/api/auth/magic-link/verify'
    | '/api/v1/models/$modelId'
    | '/api/v1/models/$modelId/versions'
    | '/api/v1/models/$modelId/files/$fileId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  OrganizationCreateRoute: typeof OrganizationCreateRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ModelsRoute: typeof ApiV1ModelsRouteWithChildren
  ApiV1UploadRoute: typeof ApiV1UploadRoute
  ApiAuthMagicLinkVerifyRoute: typeof ApiAuthMagicLinkVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/organization/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/upload': {
      id: '/api/v1/upload'
      path: '/api/v1/upload'
      fullPath: '/api/v1/upload'
      preLoaderRoute: typeof ApiV1UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models': {
      id: '/api/v1/models'
      path: '/api/v1/models'
      fullPath: '/api/v1/models'
      preLoaderRoute: typeof ApiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models/$modelId': {
      id: '/api/v1/models/$modelId'
      path: '/$modelId'
      fullPath: '/api/v1/models/$modelId'
      preLoaderRoute: typeof ApiV1ModelsModelIdRouteImport
      parentRoute: typeof ApiV1ModelsRoute
    }
    '/api/auth/magic-link/verify': {
      id: '/api/auth/magic-link/verify'
      path: '/api/auth/magic-link/verify'
      fullPath: '/api/auth/magic-link/verify'
      preLoaderRoute: typeof ApiAuthMagicLinkVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models/$modelId/versions': {
      id: '/api/v1/models/$modelId/versions'
      path: '/versions'
      fullPath: '/api/v1/models/$modelId/versions'
      preLoaderRoute: typeof ApiV1ModelsModelIdVersionsRouteImport
      parentRoute: typeof ApiV1ModelsModelIdRoute
    }
    '/api/v1/models/$modelId/files/$fileId/download': {
      id: '/api/v1/models/$modelId/files/$fileId/download'
      path: '/files/$fileId/download'
      fullPath: '/api/v1/models/$modelId/files/$fileId/download'
      preLoaderRoute: typeof ApiV1ModelsModelIdFilesFileIdDownloadRouteImport
      parentRoute: typeof ApiV1ModelsModelIdRoute
    }
  }
}

interface ApiV1ModelsModelIdRouteChildren {
  ApiV1ModelsModelIdVersionsRoute: typeof ApiV1ModelsModelIdVersionsRoute
  ApiV1ModelsModelIdFilesFileIdDownloadRoute: typeof ApiV1ModelsModelIdFilesFileIdDownloadRoute
}

const ApiV1ModelsModelIdRouteChildren: ApiV1ModelsModelIdRouteChildren = {
  ApiV1ModelsModelIdVersionsRoute: ApiV1ModelsModelIdVersionsRoute,
  ApiV1ModelsModelIdFilesFileIdDownloadRoute:
    ApiV1ModelsModelIdFilesFileIdDownloadRoute,
}

const ApiV1ModelsModelIdRouteWithChildren =
  ApiV1ModelsModelIdRoute._addFileChildren(ApiV1ModelsModelIdRouteChildren)

interface ApiV1ModelsRouteChildren {
  ApiV1ModelsModelIdRoute: typeof ApiV1ModelsModelIdRouteWithChildren
}

const ApiV1ModelsRouteChildren: ApiV1ModelsRouteChildren = {
  ApiV1ModelsModelIdRoute: ApiV1ModelsModelIdRouteWithChildren,
}

const ApiV1ModelsRouteWithChildren = ApiV1ModelsRoute._addFileChildren(
  ApiV1ModelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  OrganizationCreateRoute: OrganizationCreateRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ModelsRoute: ApiV1ModelsRouteWithChildren,
  ApiV1UploadRoute: ApiV1UploadRoute,
  ApiAuthMagicLinkVerifyRoute: ApiAuthMagicLinkVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
